CREATE TABLE `NON_MEMBER` (
	`NON_MEMBER`	VARCHAR(255)	NOT NULL,
	`ORDER_PASSWORD`	INT	NULL,
	`DELIVERY_KEY`	VARCHAR(255)	NOT NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `PRODUCT_QUANTITY` (
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY`	INT	NULL,
	`PRODUCT_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `CATEGORY` (
	`CATEGORY_KEY`	VARCHAR(255)	NOT NULL,
	`CATEGORY_TYPE`	VARCHAR(50)	NULL
);

CREATE TABLE `SELLER` (
	`SELLER_KEY`	VARCHAR(255)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(20)	NULL,
	`BUSINESS_NUMBER`	INT	NULL
);

CREATE TABLE `ORDER_ITEM` (
	`ORDER_ITEM`	VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	`ORDER_PRICE`	INT	NULL,
	`ORDER_QUANTITY`	INT	NULL
);

CREATE TABLE `MEMBER_USER` (
	`MEMBER_KEY`	VARCHAR(255)	NOT NULL,
	`USER_NAME`	VARCHAR(20)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NULL,
	`USER_PASSWORD`	VARCHAR(50)	NULL,
	`DELIVERY_KEY`	VARCHAR(255)	NOT NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`MEMBER_GRADE`	VARCHAR(255)	NOT NULL,
	`ORDER_ITEM`	VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	`SELLER_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `PHASE2_REVIEW` (
	`REVIEW_KEY`	VARCHAR(255)	NOT NULL,
	`RATING(INT)`	INT	NULL,
	`CONTENT(TEXT)`	TEXT	NULL,
	`CREATE_AT(DATETIME)`	DATETIME	NULL,
	`ORDER_ITEM`	VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `DELIVERY` (
	`DELIVERY_KEY`	VARCHAR(255)	NOT NULL,
	`ORDERER_NAME`	CARCHAR(20)	NULL,
	`DELIVERY_ADDRESS`	VARCHAR(255)	NULL
);

CREATE TABLE `PAYMENT_INFO` (
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	`ORDER_DATE`	DATETIME	NULL,
	`TOTAL_PRICE`	INT	NULL,
	`STATUS`	VARCHAR(20)	NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `SHOPING_CART` (
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `MEMBER_GRADE` (
	`MEMBER_GRADE`	VARCHAR(255)	NOT NULL,
	`GRADE_NAME`	VARCHAR(20)	NULL,
	`DISCOUNT_RATE`	INT	NULL,
	`MIN_PURCHASE`	INT	NULL
);

CREATE TABLE `PRODUCT` (
	`PRODUCT_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_NAME`	VARCHAR(100)	NULL,
	`PRODUCT_PRICE`	INT	NULL,
	`PRODUCT_COLOR`	VARCHAR(30)	NULL,
	`CATEGORY_KEY`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `PRODUCT_DETAIL` (
	`PRODUCT_DETAIL`	VARCHAR(255)	NOT NULL,
	`DESCRIPTION`	TEXT	NULL,
	`IMAGE`	VARCHAR	NULL,
	`PRODUCT_KEY`	VARCHAR(255)	NOT NULL,
	`SELLER_KEY`	VARCHAR(255)	NOT NULL
);

ALTER TABLE `NON_MEMBER` ADD CONSTRAINT `PK_NON_MEMBER` PRIMARY KEY (
	`NON_MEMBER`
);

ALTER TABLE `PRODUCT_QUANTITY` ADD CONSTRAINT `PK_PRODUCT_QUANTITY` PRIMARY KEY (
	`PRODUCT_QUANTITY_KEY`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CATEGORY_KEY`
);

ALTER TABLE `SELLER` ADD CONSTRAINT `PK_SELLER` PRIMARY KEY (
	`SELLER_KEY`
);

ALTER TABLE `ORDER_ITEM` ADD CONSTRAINT `PK_ORDER_ITEM` PRIMARY KEY (
	`ORDER_ITEM`,
	`PAYMENT_KEY`
);

ALTER TABLE `MEMBER_USER` ADD CONSTRAINT `PK_MEMBER_USER` PRIMARY KEY (
	`MEMBER_KEY`
);

ALTER TABLE `PHASE2_REVIEW` ADD CONSTRAINT `PK_PHASE2_REVIEW` PRIMARY KEY (
	`REVIEW_KEY`
);

ALTER TABLE `DELIVERY` ADD CONSTRAINT `PK_DELIVERY` PRIMARY KEY (
	`DELIVERY_KEY`
);

ALTER TABLE `PAYMENT_INFO` ADD CONSTRAINT `PK_PAYMENT_INFO` PRIMARY KEY (
	`PAYMENT_KEY`
);

ALTER TABLE `SHOPING_CART` ADD CONSTRAINT `PK_SHOPING_CART` PRIMARY KEY (
	`SHOPPING_CART_KEY`
);

ALTER TABLE `MEMBER_GRADE` ADD CONSTRAINT `PK_MEMBER_GRADE` PRIMARY KEY (
	`MEMBER_GRADE`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`PRODUCT_KEY`
);

ALTER TABLE `PRODUCT_DETAIL` ADD CONSTRAINT `PK_PRODUCT_DETAIL` PRIMARY KEY (
	`PRODUCT_DETAIL`
);

ALTER TABLE `ORDER_ITEM` ADD CONSTRAINT `FK_PAYMENT_INFO_TO_ORDER_ITEM_1` FOREIGN KEY (
	`PAYMENT_KEY`
)
REFERENCES `PAYMENT_INFO` (
	`PAYMENT_KEY`
);

