CREATE TABLE `MEMBER_GRADE` (
	`MEMBER_GRADE`	VARCHAR(255)	NOT NULL,
	`GRADE_NAME`	VARCHAR(20)	NULL,
	`DISCOUNT_RATE`	INT	NULL,
	`MIN_PURCHASE`	INT	NULL,
	PRIMARY KEY (`MEMBER_GRADE`)
);

CREATE TABLE `CATEGORY` (
	`CATEGORY_KEY`	VARCHAR(255)	NOT NULL,
	`CATEGORY_TYPE`	VARCHAR(50)	NULL,
	PRIMARY KEY (`CATEGORY_KEY`)
);

CREATE TABLE `DELIVERY` (
	`DELIVERY_KEY`		VARCHAR(255)	NOT NULL,
	`ORDERER_NAME`		VARCHAR(20)	NULL,
	`DELIVERY_ADDRESS`	VARCHAR(255)	NULL,
	PRIMARY KEY (`DELIVERY_KEY`)
);

CREATE TABLE `MEMBER_USER` (
	`MEMBER_KEY`		VARCHAR(255)	NOT NULL,
	`USER_NAME`		VARCHAR(20)	NOT NULL,
	`USER_ID`		VARCHAR(50)	NULL,
	`USER_PASSWORD`		VARCHAR(50)	NULL,
	`SELLER_KEY`		VARCHAR(255)	NULL,
	`DELIVERY_KEY`		VARCHAR(255)	NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`MEMBER_GRADE`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`MEMBER_KEY`)
);

CREATE TABLE `SELLER` (
	`SELLER_KEY`		VARCHAR(255)	NOT NULL,
	`COMPANY_NAME`		VARCHAR(20)	NULL,
	`BUSINESS_NUMBER`	INT		NULL,
	PRIMARY KEY (`SELLER_KEY`)
);

CREATE TABLE `SELLER_PRODUCT` (
	`SELLER_PRODUCT_KEY`	VARCHAR(255)	NOT NULL,
	`SELLER_KEY`		VARCHAR(255)	NOT NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`SELLER_PRODUCT_KEY`)
);

CREATE TABLE `PRODUCT` (
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	`PRODUCT_NAME`		VARCHAR(100)	NULL,
	`PRODUCT_PRICE`		INT		NULL,
	`PRODUCT_COLOR`		VARCHAR(30)	NULL,
	`PRODUCT_DESCRIPTION`	TEXT		NULL,
	`CATEGORY_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`PRODUCT_KEY`)
);

CREATE TABLE `SHOPING_CART` (
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`SHOPPING_CART_KEY`)
);

CREATE TABLE `PRODUCT_QUANTITY` (
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY`	INT		NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	`ORDER_ITEM`		VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`PRODUCT_QUANTITY_KEY`)
);

CREATE TABLE `PAYMENT_INFO` (
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	`ORDER_DATE`	DATETIME	NULL,
	`TOTAL_PRICE`	INT		NULL,
	`STATUS`	VARCHAR(20)	NULL,
	`MEMBER_KEY`	VARCHAR(255)	NULL,
	PRIMARY KEY (`PAYMENT_KEY`)
);

CREATE TABLE `ORDER_ITEM` (
	`ORDER_ITEM`		VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`		VARCHAR(255)	NOT NULL,
	`ORDER_PRICE`		INT		NULL,
	`ORDER_QUANTITY`	INT		NULL,
	`MEMBER_KEY`		VARCHAR(255)	NULL,
	PRIMARY KEY (`ORDER_ITEM`)
);

CREATE TABLE `NON_MEMBER` (
	`NON_MEMBER`		VARCHAR(255)	NOT NULL,
	`ORDER_PASSWORD`	INT		NULL,
	`DELIVERY_KEY`		VARCHAR(255)	NOT NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`NON_MEMBER`)
);

CREATE TABLE `PHASE2_REVIEW` (
	`REVIEW_KEY`	VARCHAR(255)	NOT NULL,
	`RATING`	INT		NULL,
	`CONTENT`	TEXT		NULL,
	`CREATE_AT`	DATETIME	NULL,
	`ORDER_ITEM`	VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`REVIEW_KEY`)
);

CREATE TABLE `PHASE2_PRODUCT_IMAGES` (
	`PRODUCT_IMAGES`	VARCHAR(255)	NOT NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL
);
