-- =============================================
-- SHOPPING MALL DATABASE
-- 수정 내역:
-- 1. MEMBER_USER: SELLER_KEY, DELIVERY_KEY → NULL 허용
-- 2. MEMBER_USER: PRODUCT_KEY, ORDER_ITEM, PAYMENT_KEY → 삭제
-- 3. ORDER_ITEM: MEMBER_KEY 추가 (회원 참조)
-- 4. PAYMENT_INFO: MEMBER_KEY 추가 (회원 참조)
-- =============================================

CREATE TABLE `MEMBER_GRADE` (
	`MEMBER_GRADE`	VARCHAR(255)	NOT NULL,
	`GRADE_NAME`	VARCHAR(20)	NULL,
	`DISCOUNT_RATE`	INT	NULL,
	`MIN_PURCHASE`	INT	NULL,
	PRIMARY KEY (`MEMBER_GRADE`)
);

CREATE TABLE `CATEGORY` (
	`CATEGORY_KEY`	VARCHAR(255)	NOT NULL,
	`CATEGORY_TYPE`	VARCHAR(50)	NULL,
	PRIMARY KEY (`CATEGORY_KEY`)
);

CREATE TABLE `DELIVERY` (
	`DELIVERY_KEY`	VARCHAR(255)	NOT NULL,
	`ORDERER_NAME`	VARCHAR(20)	NULL,
	`DELIVERY_ADDRESS`	VARCHAR(255)	NULL,
	PRIMARY KEY (`DELIVERY_KEY`)
);

CREATE TABLE `MEMBER_USER` (
	`MEMBER_KEY`		VARCHAR(255)	NOT NULL,
	`USER_NAME`		VARCHAR(20)	NOT NULL,
	`USER_ID`		VARCHAR(50)	NULL,
	`USER_PASSWORD`		VARCHAR(50)	NULL,
	`SELLER_KEY`		VARCHAR(255)	NULL,		-- 수정: NOT NULL → NULL (판매자가 아닌 회원도 있음)
	`DELIVERY_KEY`		VARCHAR(255)	NULL,		-- 수정: NOT NULL → NULL (배송지 없어도 됨)
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`MEMBER_GRADE`		VARCHAR(255)	NOT NULL,
	-- 삭제: PRODUCT_KEY (SELLER 테이블에서 관리)
	-- 삭제: ORDER_ITEM (ORDER_ITEM 테이블에서 MEMBER_KEY로 관리)
	-- 삭제: PAYMENT_KEY (직접 저장 안 함)
	PRIMARY KEY (`MEMBER_KEY`)
);

CREATE TABLE `SELLER` (
	`SELLER_KEY`		VARCHAR(255)	NOT NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	`COMPANY_NAME`		VARCHAR(20)	NULL,
	`BUSINESS_NUMBER`	INT		NULL,
	PRIMARY KEY (`SELLER_KEY`)
);

CREATE TABLE `PRODUCT` (
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	`PRODUCT_NAME`		VARCHAR(100)	NULL,
	`PRODUCT_PRICE`		INT		NULL,
	`PRODUCT_COLOR`		VARCHAR(30)	NULL,
	`PRODUCT_DESCRIPTION`	TEXT		NULL,
	`CATEGORY_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`PRODUCT_KEY`)
);

CREATE TABLE `SHOPING_CART` (
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`SHOPPING_CART_KEY`)
);

CREATE TABLE `PRODUCT_QUANTITY` (
	`PRODUCT_QUANTITY_KEY`	VARCHAR(255)	NOT NULL,
	`PRODUCT_QUANTITY`	INT		NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL,
	`ORDER_ITEM`		VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`PRODUCT_QUANTITY_KEY`)
);

CREATE TABLE `PAYMENT_INFO` (
	`PAYMENT_KEY`	VARCHAR(255)	NOT NULL,
	`ORDER_DATE`	DATETIME	NULL,
	`TOTAL_PRICE`	INT		NULL,
	`STATUS`	VARCHAR(20)	NULL,
	`MEMBER_KEY`	VARCHAR(255)	NULL,		-- 추가: 어떤 회원의 결제인지 참조
	PRIMARY KEY (`PAYMENT_KEY`)
);

CREATE TABLE `ORDER_ITEM` (
	`ORDER_ITEM`		VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`		VARCHAR(255)	NOT NULL,
	`ORDER_PRICE`		INT		NULL,
	`ORDER_QUANTITY`	INT		NULL,
	`MEMBER_KEY`		VARCHAR(255)	NULL,		-- 추가: 어떤 회원의 주문인지 참조
	PRIMARY KEY (`ORDER_ITEM`)
);

CREATE TABLE `NON_MEMBER` (
	`NON_MEMBER`		VARCHAR(255)	NOT NULL,
	`ORDER_PASSWORD`	INT		NULL,
	`DELIVERY_KEY`		VARCHAR(255)	NOT NULL,
	`SHOPPING_CART_KEY`	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`NON_MEMBER`)
);

CREATE TABLE `PHASE2_REVIEW` (
	`REVIEW_KEY`		VARCHAR(255)	NOT NULL,
	`RATING`		INT		NULL,
	`CONTENT`		TEXT		NULL,
	`CREATE_AT`		DATETIME	NULL,
	`ORDER_ITEM`		VARCHAR(255)	NOT NULL,
	`PAYMENT_KEY`		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (`REVIEW_KEY`)
);

CREATE TABLE `PHASE2_PRODUCT_IMAGES` (
	`PRODUCT_IMAGES`	VARCHAR(255)	NOT NULL,
	`PRODUCT_KEY`		VARCHAR(255)	NOT NULL
);
